INSERT INTO TBL_STUDENT(STUDENT_EMAIL,STUDENT_CPF,STUDENT_LOCATION,STUDENT_NAME) VALUES('Eduardo@gmail.com','423432452','Casa do Eduardo','Eduardo');
INSERT INTO TBL_STUDENT(STUDENT_EMAIL,STUDENT_CPF,STUDENT_LOCATION,STUDENT_NAME) VALUES('David@gmail.com','3453457858','Casa do David','David');
